### PR TITLE
Bug - restore transaction history speed improvement

### LINKED ISSUE #216: Tx History recovery very slow
The transaction history parsing algorithm is very, VERY slow right now.  When the wallet has 100+ SLP transactions, it can take multiple minutes to parse the results.

It must be improved.

### PR DESCRIPTION
**Pull request by SpicyPete**
# Summary

* Use the default `bitdb` and `slpdb` return address types for historical comparisons.
* New hook to convert address formats
* re-increase the SLP history to 500
* re-increase the BCH history to 30
* Transaction history parsing is now ~10 seconds, down from ~6 minutes.  On phones tested so far.
* Improved transaction history visuals

fixes #216

### CODE REVIEW

File: data/transactions/actions.ts [hunk 1]
```diff
@@ -19,6 +19,8 @@ import { Transaction } from "./reducer";
 import { transactionsLatestBlockSelector } from "../selectors";
 import { transactionsSelector } from "./selectors";
 
+const appendBCHPrefix = (target: string) => `bitcoincash:${target}`;
```
Comment (paOol) [inline data/transactions/actions.ts:22]: suggestion: make a function that you can apply on all address strings and will add the prefix if its missing.

some pseudo logic

  let split = string.split(':')[1];

  if (split === undefined) {
   //    
  }

**Review by paOol — APPROVED** [review]

File: data/transactions/actions.ts (hunk 1 above)
Comment (SpicyPete) [reply data/transactions/actions.ts:22]: Noted, good suggestion.
Let's improve this in the next PR.
