### PR TITLE
Bug - BIP 70 with OP_RETURN fee calculation

### LINKED ISSUE #201: BIP70 Fee Calculation too low for transactions with large OP_RETURN outputs
Wallet will produce with 400 error after scanning BIP70 invoice and swiping to pay if the invoice contains an OP_RETURN output with a message of longer than 60 characters or so.

From slack discussion:

> In Badger it does the calculation here: https://github.com/Bitcoin-com/badger-mobile/blob/develop/utils/bip70-utils.js#L314It's expecting P2PKH input and outputs only. P2SH is smaller as an output, so P2SH output addresses work just fine. sufficient fee. Some logic could be put in there to check for an op return and add that amount ot the byte count.

### PR DESCRIPTION
**Pull request by SpicyPete**
Fixing issue where BIP70 with OP_RETURNS are not paying fee correct

fixes #201

### CODE REVIEW

File: utils/bip70-utils.js [hunk 1]
```diff
@@ -303,6 +303,18 @@ const signAndPublishPaymentRequestTransaction = async (
   let totalUtxoAmount = 0;
   const transactionBuilder = new SLP.TransactionBuilder("mainnet");
 
+  let opReturnLength = null;
+  if (
+    paymentRequest.outputs[0].amount.eq(0) &&
+    !paymentRequest.outputs[0].tokenAmount
+  ) {
+    const asBuffer = Buffer.from(paymentRequest.outputs[0].script, "hex");
+    opReturnLength = asBuffer.length;
```
Comment (SpendBCH) [inline utils/bip70-utils.js]: Are you able to use byteLength here? It should be more accurate

Comment (SpicyPete) [reply utils/bip70-utils.js]: Updated this to use `Buffer.byeLength()`
